"""Metadata invariants for the compliance DocTypes generated by compliance_controls.py.

`install.after_migrate` syncs COMPLIANCE_DOCTYPES over whatever the DocType JSON exports
put in the database, so the two definitions must agree — when they drift, a migrate leaves
Select fields with truncated options and Frappe's own `_validate_selects` then rejects every
save that sets a calculated status ("Value X cannot be in options").
"""

import ast
import json
from pathlib import Path

import frappe
from frappe.tests.utils import FrappeTestCase

from hr_suite.hr_suite import compliance_controls

APP_ROOT = Path(compliance_controls.__file__).resolve().parents[2]
DOCTYPE_ROOT = APP_ROOT / "hr_suite" / "doctype"
SYNCED_KEYS = ("options", "default", "fieldtype", "reqd", "read_only", "fetch_from")

# Every status a calculate_*/apply_* helper assigns or compares against, per DocType.
FUNCTION_DOCTYPE = {
	"calculate_disability_ratio": "Disability Employment Compliance",
	"apply_disability_accommodation_catalog": "Disability Employment Compliance",
	"calculate_final_settlement_dates": "Final Settlement SLA",
	"calculate_work_arrangement_dates": "Work Arrangement Control",
	"calculate_working_time_status": "Working Time Compliance Check",
	"calculate_statutory_record_counts": "Statutory HR Records Register",
	"calculate_inspection_fine_dates": "Inspection Fine SLA",
	"calculate_ministry_filing_status": "Ministry Filing Tracker",
	"apply_disciplinary_catalog_recommendation": "Disciplinary Procedure",
	"calculate_provider_compliance_status": "Recruitment Service Provider Compliance",
	"calculate_provider_complaint_status": "Recruitment Provider Complaint",
	"calculate_training_agreement_status": "Training Agreement",
	"create_final_settlement_from_termination": "Final Settlement SLA",
}


def _generated_fields(name):
	for definition in compliance_controls.COMPLIANCE_DOCTYPES:
		if definition["name"] == name:
			return {row["fieldname"]: row for row in definition["fields"]}
	return {}


def _json_export(name):
	slug = name.lower().replace(" ", "_").replace("-", "_")
	path = DOCTYPE_ROOT / slug / f"{slug}.json"
	if not path.exists():
		return None
	return json.loads(path.read_text())


class TestComplianceMetadata(FrappeTestCase):
	def test_select_defaults_are_listed_in_options(self):
		for definition in compliance_controls.COMPLIANCE_DOCTYPES:
			for row in definition["fields"]:
				if row.get("fieldtype") != "Select" or not row.get("default"):
					continue
				options = (row.get("options") or "").split("\n")
				self.assertIn(row["default"], options, f"{definition['name']}.{row['fieldname']}")

	def test_json_exports_match_the_generator(self):
		for definition in compliance_controls.COMPLIANCE_DOCTYPES:
			exported = _json_export(definition["name"])
			if exported is None:
				continue
			generated = _generated_fields(definition["name"])
			for row in exported["fields"]:
				gen = generated.get(row["fieldname"])
				if not gen:
					continue
				for key in SYNCED_KEYS:
					if key in gen:
						self.assertEqual(
							row.get(key),
							gen[key],
							f"{definition['name']}.{row['fieldname']}.{key} drifted from the generator",
						)

	def test_calculated_statuses_are_valid_select_values(self):
		"""Every literal a compliance helper writes to a Select must be one of its options."""
		source = Path(compliance_controls.__file__).read_text()
		tree = ast.parse(source)

		for func in [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in FUNCTION_DOCTYPE]:
			fields = _generated_fields(FUNCTION_DOCTYPE[func.name])
			for node in ast.walk(func):
				pairs = []
				target = node.targets[0] if isinstance(node, ast.Assign) and len(node.targets) == 1 else None
				if isinstance(target, ast.Attribute):
					pairs.append((target.attr, node.value))
				elif isinstance(node, ast.Dict):
					pairs.extend(
						(key.value, value)
						for key, value in zip(node.keys, node.values, strict=False)
						if isinstance(key, ast.Constant) and isinstance(key.value, str)
					)
				for fieldname, value in pairs:
					row = fields.get(fieldname)
					if not row or row.get("fieldtype") != "Select":
						continue
					if not (isinstance(value, ast.Constant) and isinstance(value.value, str)):
						continue
					options = (row.get("options") or "").split("\n")
					self.assertIn(
						value.value, options,
						f"{func.name} writes {fieldname}={value.value!r} which is not an option",
					)

	def test_number_card_and_chart_filters_are_valid_json(self):
		"""filters_json is a JSON string inside a JSON file — a split at an escaped newline
		leaves it unparseable and the card fails to render."""
		for folder in ("number_card", "dashboard_chart"):
			for path in (APP_ROOT / "hr_suite" / folder).glob("*/*.json"):
				raw = (json.loads(path.read_text()).get("filters_json") or "").strip()
				if not raw:
					continue
				try:
					filters = json.loads(raw)
				except ValueError as exc:
					self.fail(f"{path.parent.name}: filters_json is not valid JSON ({exc}): {raw!r}")
				self.assertIsInstance(filters, list, path.parent.name)

	def test_number_card_and_chart_filters_use_real_option_values(self):
		for folder in ("number_card", "dashboard_chart"):
			for path in (APP_ROOT / "hr_suite" / folder).glob("*/*.json"):
				config = json.loads(path.read_text())
				doctype = config.get("document_type")
				if not doctype or not frappe.db.exists("DocType", doctype):
					continue
				meta = frappe.get_meta(doctype)
				for condition in json.loads(config.get("filters_json") or "[]"):
					if not (isinstance(condition, list) and len(condition) == 4 and condition[2] == "="):
						continue
					df = meta.get_field(condition[1])
					if not df or df.fieldtype != "Select":
						continue
					options = [option for option in (df.options or "").split("\n") if option]
					if not options:
						continue
					self.assertIn(
						condition[3], options,
						f"{path.parent.name}: {doctype}.{condition[1]} filter value is not a valid option",
					)
